### ISSUE TITLE
link to npm and action to publish

### ISSUE THREAD

**Issue by lastlink** [ryanrosello-og/cypress-harvester#11]
- could you add a link to the npm package, either in the readme or as a url for the repository which you can find under settings
- also you could add an action to automatically publish new npm versions [see](https://github.com/funktechno/texthighlighter/blob/dev/.github/workflows/publish.yml) my example. You'll need to go into settings > secrets > npm and add your publisher ci token from npm.

@ryanrosello-og

**Comment by ryanrosello-og** [comment]
@lastlink  good idea,  I will look into this.
