### ISSUE TITLE
False negative assertion error

### ISSUE THREAD

**Issue by kodriscollics** [ryanrosello-og/cypress-harvester#13]
Environment:

- Cypress 8.3.0 Cypress
- Cypress-Harvester plugin 1.1.0
- IntelliJ IDEA 2021.2 Ultimate
- Chrome Version 92.0.4515.159

Issue:
I have been seeing this issue since I first started using cypress-harvester, but I thought it was a cypress-intelliJ-reporter issue (because of a cypress mocha error that is thrown when this test is run within IntelliJ). In my troubleshooting efforts, I finally just closed down IntelliJ to eliminate that from the equation and ran the tests from both a Windows CMD console and the Cypress Test Runner GUI.

This is the test code. It fails the sorting assertion, but the screenshots show  that the sorting is correct. The test fails while sorting both the Unit Name column and the Date Received column:

                //Sorting by UNIT NAME asc
                cy.task('log', '  Testing sorted by UNIT NAME ascending...')
                cy.getByID('unitNameNumberHeader').click()

                cy.get('#dataTable')
                    .should('have.length.above', 0)
                    .scrapeTable()
                    .then((table) => {
                            expect(table.columnLabels).to.deep.eq([
                                '',
                                'Task #',
                                'Unit Name ↓',
                                'Date Received',
                                'Type',
                                'Group'])

                            expect(table.isPropertySorted(['unit_name'], ['asc'])).to.be.true
                        }
                    )

                //Sorting by DATE RECEIVED asc
                cy.task('log', '  Testing sorted by DATE RECEIVED ascending...')
                cy.getByID('dateReceivedHeader').click()

                cy.get('#dataTable')
                    .should('have.length.above', 0)
                    .scrapeTable()
                    .then((table) => {
                            expect(table.columnLabels).to.deep.eq([
                                '',
                                'Task #',
                                'Unit Name',
                                'Date Received ↓',
                                'Type',
                                'Group'])

                           expect(table.isPropertySorted(['date_received'], ['asc'])).to.be.true 
                        }
                    )

This is a screenshot of the CMD console for the tests:

![UnitNameSortFailure-1](https://user-images.githubusercontent.com/75755773/131553090-16b1c3e7-e4f1-4c08-a1d4-ccc4224c9681.png)

These are screenshots from the Cypress Test Runner GUI for each of the tests. They show the columns in question sorted properly, but the assertion insists they are not:

UNIT NAME SORT FAILURE
![UnitNameSortFailure-3](https://user-images.githubusercontent.com/75755773/131553621-702a21a4-16b6-4144-8a54-b0cc0d8018dd.png)

DATE RECEIVED SORT FAILURE
![DateSortFailure-1](https://user-images.githubusercontent.com/75755773/131553724-a2f8369d-da59-47c7-bacd-b1c6ba2bb3eb.png)

I'm wondering, looking at the data, if the sort routine is not liking that an entry under UNIT NAME starts with non-alphabetic chars... i.e. "(Def" and, that the DATE RECEIVED column maybe is being evaluated by harvester using a date code/format instead of as the text is displayed. IDK... just guessing.

**Comment by kodriscollics** [comment]
I temporarily modified the DB to eliminate entries that have a unit name starting with an non-alphabetic character. In this case, a left parenthesis. And, the test on that column passed. This is not something I can do in a live test as unit names in our case can sometimes start with a "(" and/or end with a right parenthesis ")"  and/or contain numerals e.g.... (Default Unit 0). 

Still not sure what is happening with the date, but again, my suspicion is a date code compare vs. straight text.

**Comment by ryanrosello-og** [comment]
thanks for raising this.  I will look into soon

**Comment by ryanrosello-og** [comment]
@kodriscollics this is fixed in 1.2.0.  See updated doc => https://github.com/ryanrosello-og/cypress-harvester#date-assertions

**Comment by kodriscollics** [comment]
After updating, Cypress fails on test startup. Getting the following error. I haven't changed any of the configuration. Just updated harvester:

Oops...we found an error preparing this test file:

  cypress\support\index.js

The error was:

Error: Webpack Compilation Error
./node_modules/cypress-harvester/cypress/support/commands.js
Module not found: Error: Can't resolve 'date-fns/get_time' in 'C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\support'
resolve 'date-fns/get_time' in 'C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\support'
  Parsed request is a module
  using description file: C:\dev\AdminApp-QA\node_modules\cypress-harvester\package.json (relative path: ./cypress/support)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\support\node_modules doesn't exist or is not a directory
      C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\node_modules doesn't exist or is not a directory
      C:\dev\AdminApp-QA\node_modules\cypress-harvester\node_modules doesn't exist or is not a directory
      C:\dev\AdminApp-QA\node_modules\node_modules doesn't exist or is not a directory
      C:\dev\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\dev\AdminApp-QA\node_modules
        using description file: C:\dev\AdminApp-QA\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\dev\AdminApp-QA\package.json (relative path: ./node_modules/date-fns/get_time)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.json doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.jsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.mjs doesn't exist
            .coffee
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.coffee doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time.tsx doesn't exist
            as directory
              C:\dev\AdminApp-QA\node_modules\date-fns\get_time doesn't exist
[C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\support\node_modules]
[C:\dev\AdminApp-QA\node_modules\cypress-harvester\cypress\node_modules]
[C:\dev\AdminApp-QA\node_modules\cypress-harvester\node_modules]
[C:\dev\AdminApp-QA\node_modules\node_modules]
[C:\dev\node_modules]
[C:\node_modules]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.js]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.json]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.jsx]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.mjs]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.coffee]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.ts]
[C:\dev\AdminApp-QA\node_modules\date-fns\get_time.tsx]
 @ ./node_modules/cypress-harvester/cypress/support/commands.js 28:18-46
 @ ./cypress/support/commands.js
 @ ./cypress/support/index.js

**Comment by ryanrosello-og** [comment]
I will investigate

**Comment by ryanrosello-og** [comment]
@kodriscollics this should be fixed in 1.3.0
I will keep this issue open until you get this working on your end.

**Comment by ryanrosello-og** [comment]
Would you be able to show me the full output for this?  You'll need to open up devTools and go to the Console tab

![2021-11-03_6-56-09](https://user-images.githubusercontent.com/50574915/139950442-cd2444a4-76d5-4445-a075-747a3bd17940.png)
e

**Comment by kodriscollics** [comment]
Sure, no problem:

Console was cleared
cypress_runner.js:191069 Command:  wrap
cypress_runner.js:191069 Yielded:  DataTable
DevTools failed to load source map: Could not load content for https://dev-56789660.okta.com/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular/angular.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular-resource/angular-resource.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular-ui-router/release/angular-ui-router.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/ng-idle/angular-idle.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/moment/min/moment.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angularjs-dropdown-multiselect/dist/maps/angularjs-dropdown-multiselect.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular/angular.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular-resource/angular-resource.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angular-ui-router/release/angular-ui-router.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/moment/min/moment.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/angularjs-dropdown-multiselect/dist/maps/angularjs-dropdown-multiselect.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for https://my-app.myCompany.org/my-app/lib/ng-idle/angular-idle.map: Unexpected token < in JSON at position 0

**Comment by ryanrosello-og** [comment]
hey @kodriscollics , I was after the output similar to ...
![2021-11-03_08-26-47](https://user-images.githubusercontent.com/50574915/139960487-96d069ff-cf23-42fa-a2cc-476616dab1e3.jpg)

Cheers

**Comment by kodriscollics** [comment]
@ryanrosello-og ... Doh! My bad.

cypress_runner.js:191077 Console was cleared
cypress_runner.js:191069 Command:  wrap
cypress_runner.js:191069 Yielded:  
DataTable
columnLabels: Array(6)
0: ""
1: "Task #"
2: "Unit Name"
3: "Date Received ↓"
4: "Type"
5: "Group"
length: 6
[[Prototype]]: Array(0)
data: Array(25)
0:
column_name_0: ""
date_received: "07 Dec 2020"
group: "Limited"
task: "4296389"
type: "TYPE (221)"
unit_name: "Jones Falls Unit (443)"
[[Prototype]]: Object
1:
column_name_0: ""
date_received: "11 Mar 2021"
group: "Non-Accessible"
task: "4328628"
type: "TYPE (33)"
unit_name: "Venezuela Unit (20558)"
[[Prototype]]: Object
2:
column_name_0: ""
date_received: "11 Mar 2021"
group: "Moved"
task: "4328630"
type: "TYPE (35)"
unit_name: "Venezuela Unit (20558)"
[[Prototype]]: Object
3:
column_name_0: ""
date_received: "14 Mar 2021"
group: "Grounds"
task: "4329675"
type: "TYPE (46)"
unit_name: "Ashton Park Unit (168)"
[[Prototype]]: Object
4:
column_name_0: ""
date_received: "16 Mar 2021"
group: "Data Create"
task: "4330121"
type: "TYPE (103)"
unit_name: "Maryland Baltimore Unit (2002)"
[[Prototype]]: Object
5:
column_name_0: ""
date_received: "21 Mar 2021"
group: "Non-Accessible"
task: "4331571"
type: "UNKNOWN (107)"
unit_name: "El Progreso Unit (205)"
[[Prototype]]: Object
6:
column_name_0: ""
date_received: "23 Mar 2021"
group: "Limited"
task: "4332372"
type: "TYPE (108)"
unit_name: "Los Gatos Unit (145)"
[[Prototype]]: Object
7:
column_name_0: ""
date_received: "24 Mar 2021"
group: "Moved"
task: "4332740"
type: "TYPE (117)"
unit_name: "Powhatan Unit (373)"
[[Prototype]]: Object
8:
column_name_0: ""
date_received: "28 Mar 2021"
group: "Non-Accessible"
task: "4333853"
type: "TYPE (220)"
unit_name: "Preston Unit (272)"
[[Prototype]]: Object
9:
column_name_0: ""
date_received: "29 Mar 2021"
group: "Supervisor"
task: "4334037"
type: "TYPE (25)"
unit_name: "(Default Unit) (0)"
[[Prototype]]: Object
10:
column_name_0: ""
date_received: "29 Mar 2021"
group: "Data Create"
task: "4334174"
type: "TYPE (29)"
unit_name: "Denver Unit (2008)"
[[Prototype]]: Object
11:
column_name_0: ""
date_received: "29 Mar 2021"
group: "Team Update"
task: "4334183"
type: "TYPE (30)"
unit_name: "New York Unit (2075)"
[[Prototype]]: Object
12:
column_name_0: ""
date_received: "29 Mar 2021"
group: "Limited"
task: "4334218"
type: "TYPE (34)"
unit_name: "Chicago Unit (2013)"
[[Prototype]]: Object
13:
column_name_0: ""
date_received: "01 Apr 2021"
group: "Supervisor"
task: "4335296"
type: "UNKNOWN TYPE (50)"
unit_name: "San Pablo Unit (2047)"
[[Prototype]]: Object
14:
column_name_0: ""
date_received: "01 Apr 2021"
group: "Supervisor"
task: "4335307"
type: "UNKNOWN TYPE (50)"
unit_name: "San Pablo Unit (2047)"
[[Prototype]]: Object
15:
column_name_0: ""
date_received: "01 Apr 2021"
group: "Supervisor"
task: "4335372"
type: "TYPE (106)"
unit_name: "Cauayan Unit (2038)"
[[Prototype]]: Object
16:
column_name_0: ""
date_received: "01 Apr 2021"
group: "Team Update"
task: "4335414"
type: "TYPE (123)"
unit_name: "(Default Unit) (0)"
[[Prototype]]: Object
17:
column_name_0: ""
date_received: "01 Apr 2021"
group: "Grounds"
task: "4335416"
type: "TYPE (124)"
unit_name: "(Default Unit) (0)"
[[Prototype]]: Object
18:
column_name_0: ""
date_received: "03 Apr 2021"
group: "Supervisor"
task: "4336272"
type: "TYPE (200)"
unit_name: "Cauayan Unit (2038)"
[[Prototype]]: Object
19:
column_name_0: ""
date_received: "06 Apr 2021"
group: "Team Update"
task: "4337111"
type: "TYPE (23)"
unit_name: "Quetzaltenango Unit (2025)"
[[Prototype]]: Object
20:
column_name_0: ""
date_received: "07 Apr 2021"
group: "Non-Accessible"
task: "4337259"
type: "TYPE (26)"
unit_name: "Philippines Unit (462)"
[[Prototype]]: Object
21:
column_name_0: ""
date_received: "07 Apr 2021"
group: "Limited"
task: "4337286"
type: "TYPE (27)"
unit_name: "Philippines Unit (4632)"
[[Prototype]]: Object
22:
column_name_0: ""
date_received: "09 Apr 2021"
group: "Grounds"
task: "4337838"
type: "TYPE (31)"
unit_name: "Billings Unit (2003)"
[[Prototype]]: Object
23:
column_name_0: ""
date_received: "11 Apr 2021"
group: "Data Create"
task: "4338457"
type: "TYPE (36)"
unit_name: "Pleasant Valley Unit (20)"
[[Prototype]]: Object
24:
column_name_0: ""
date_received: "12 Apr 2021"
group: "Team Update"
task: "4338706"
type: "TYPE (45)"
unit_name: "Blackfoot Unit (22)"
[[Prototype]]: Object
length: 25
[[Prototype]]: Array(0)
exportStatus: ""
info: ""
propertyNames: Array(6)
0: "column_name_0"
1: "task"
2: "unit_name"
3: "date_received"
4: "type"
5: "group"
length: 6
[[Prototype]]: Array(0)
[[Prototype]]: Object

**Comment by ryanrosello-og** [comment]
try
```
cy.get('#your_table')
  .scrapeTable({ dateColumns: [3] })
  .then((table) => {
   expect(table.isPropertySorted(['date_received'], ['asc'])).to.be.true
  });
```

**Comment by ryanrosello-og** [comment]
This is entirely a new option, its documented here https://github.com/ryanrosello-og/cypress-harvester#date-assertions
