### ISSUE TITLE
The isPropertySorted function appears to return true regardless of parameters used--even invalid parameters

### ISSUE THREAD

**Issue by kodriscollics** [ryanrosello-og/cypress-harvester#4]
I love this plugin! It is exactly what I've been looking for.

I have noticed, however, that the column sorting function isPropertySorted resolves to true no matter what parameters are used. For example, the table I am testing against has the following columns:

    'Task',
    'Name',
    'Date Received',
    'Type'

If I use the following in a test (with the invalid parameters of "blah" and "blahblah") it still resolves to true and the test passes:

                cy.get('#dataTable')
                    .scrapeTable()
                    .then((table) => {
                            expect(table.isPropertySorted(['blah'], ['blahblah'])).to.be.true;
                        }
                    )

**Comment by ryanrosello-og** [comment]
Thanks for the feedback.  I will look into this.

**Comment by ryanrosello-og** [comment]
This issue has been fixed in #5, validation implemented.

When an invalid column name is provided to the `isPropertySorted()` function it will return an error similar to:

`Unexpected columns names encountered [non-existent_column], expected columns name to be one of [first_name,last_name,gender,age]`

**Comment by kodriscollics** [comment]
Thank you for looking into this. You're awesome. The check for "desc" and "asc" works great. However the column name check is not working right for me still.  I'll open another issue to document it.

Thanks again!
