### ISSUE TITLE
The isPropertySorted function is not getting the correct column names, causing the sort assertion to fail

### ISSUE THREAD

**Issue by kodriscollics** [ryanrosello-og/cypress-harvester#7]
cypress-harvester@1.0.3
cypress@7.5.0

I have the following column names for a table on a page that I am working with---note that these have been updated by the developer since the previous issue entered involving this function: 

        ''    (note... this is the placeholder for a checkbox used for selecting all rows in the table.)
        'Task # ↑',   (note... the up-arrow ↑ indicates this is the col used for sorting & the sort direction. It moves from col to col.)
        'Unit Name',
        'Date Received',
        'Type'
        'Previously Assigned To'

If I use the following assertion in my test code, I get the subsequent message:

            cy.get('#dataTable')
                .scrapeTable()
                .then((table) => {
                        expect(table.isPropertySorted(['Task # ↑'], ['desc'])).to.be.true;
                    }
                )

"AssertionError: expected [Error: Unexpected columns names encountered [Task # ↑], expected columns name to be one of [column_name_0,task,unit_name,date_received,type,previously_assigned_to]] to be true"

To check that the column names I'm specifying are correct, I added the following assertion to my test code, which passes:

                cy.get('#dataTable')
                    .scrapeTable()
                    .then((table) => {
                            expect(table.columnLabels).to.deep.eq([
                                '',
                                'Task # ↑',
                                'Unit Name',
                                'Date Received',
                                'Type',
                                'Previously Assigned To'])

See the attached screenshots of the table and the dev code which generates it:

<img width="916" alt="columnNames" src="https://user-images.githubusercontent.com/75755773/122971318-282dd680-d34c-11eb-935a-317448dd7e9d.PNG">
<img width="612" alt="codeSnipett" src="https://user-images.githubusercontent.com/75755773/122971320-28c66d00-d34c-11eb-9fd2-7f4047eba020.PNG">

Thanks!

**Comment by ryanrosello-og** [comment]
hey @kodriscollics 

Would you be able to try:

```javascript
    cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['task'], ['desc'])).to.be.true;
      });
```

The api is a little confusing, the `isPropertySorted` function accepts an array of the properties not the actual column names.  This done deliberately since it was difficult to exactly match against column names in situations where special characters exists as part of the column.

![2021-06-23_10-00-06](https://user-images.githubusercontent.com/50574915/123014562-dcd9fd80-d409-11eb-9515-cfbabb454f95.png)

**Comment by kodriscollics** [comment]
Thanks for getting back with me @ryanrosello-og. I'm OK using propertyNames for my tests instead of columnLabels. 

As you requested, I inserted the code you asked me to try into the test. The assertion did pass. As a check, I changed the sortOrder parameter to 'asc' (expecting it to fail) but it also passed. I then tried every other valid "propertyName" (i.e. task, unit_ name, date_ received,type and previously_assigned_to) in combination with both sort order parameters (desc and asc) and every combination also passed. So, regardless of which column the data was actually sorted on, the test always passes using any column propertyName/sortOrder combination.

In the example images shown below from the Cypress GUI, the column was actually sorted on task/asc but the assertion was set to:

      expect(table.isPropertySorted(['unit_name'], ['desc'])).to.be.true;

...
<img width="933" alt="columnNames2" src="https://user-images.githubusercontent.com/75755773/123162777-41a74f00-d42e-11eb-8785-844a0bbb75c1.PNG">

<img width="588" alt="cypressImage1" src="https://user-images.githubusercontent.com/75755773/123162805-48ce5d00-d42e-11eb-89e1-5f6d4401f7f8.PNG">

<img width="516" alt="debug2" src="https://user-images.githubusercontent.com/75755773/123162817-4e2ba780-d42e-11eb-8899-18e4e3a6fdbc.PNG">

which still passed.

Thanks again for your help and for hanging in there with me!
Kent.

**Comment by ryanrosello-og** [comment]
Thanks @kodriscollics
This is definitely a bug, I reproduced using the test below:

```javascript
/// <reference types="cypress" />
describe('isPropertySorted', () => {
  it('bug', () => {
    cy.visit('https://material.angular.io/components/table/overview')
    cy.get('table-basic-example table').scrapeTable({ 
      decimalColumns: [0], 
      removeAllNewlineCharacters: true
    }).then((table) => {
      // should fail
      expect(
        table.isPropertySorted(['no','name'], ['asc', 'asc'])
      ).to.be.true;
    })
  })
})
```

I tracked it down to an issue with the lodash orderyBy function.  https://github.com/lodash/lodash/issues/4214

Leave this with me,  I will look for other alternatives to the lodash orderBy function

**Comment by kodriscollics** [comment]
@ryanrosello-og ... will do. Thanks again!!

**Comment by ryanrosello-og** [comment]
I just noticed something in your screenshot above.  This property `data` seems to be empty?

![2021-06-25_11-15-00](https://user-images.githubusercontent.com/50574915/123355835-d1bdd380-d5a9-11eb-858c-24ef6d6a923f.png)

Could you try adding a guard into your test prior to calling `.scrapeTable() ...` to ensure data exists in the table?

e.g.
```javascript
  cy.get('#dataTable tr').should('have.length.above',5)   // use Cypress 'should' to wait for data to load?
  cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
              expect(table.isPropertySorted(['Task # ↑'], ['desc'])).to.be.true;
          }
      )
```

It seems calling the `.isPropertySorted()` function will always return `true` when theres no data in table:

```html
  <table id="onlyHeaders">
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
      <td>Gender</td>
      <td>Age</td>
    </tr>
  </table>
```

```javascript
  it.only('empty table', () => {
    cy.get('#onlyHeaders').scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['first_name', 'age'], ['asc', 'desc'])).to.be.true;
        expect(table.isPropertySorted(['gender'], ['asc'])).to.be.true;
        expect(table.isPropertySorted(['gender'], ['desc'])).to.be.true;
        expect(table.isPropertySorted(['last_name'], ['desc'])).to.be.true;
        expect(table.isPropertySorted(['last_name', 'first_name'], ['asc', 'desc'])).to.be.true;
      })
  })
```

Since theres no data in the `data` property, `isPropertySorted()` will always return true

![2021-06-25_11-30-23](https://user-images.githubusercontent.com/50574915/123356370-f6667b00-d5aa-11eb-8cb2-eb5b4b1d0240.png)

I will add another validation to ensure data exists when the `isPropertySorted()` is called.  This will then result in the error below:

![2021-06-25_11-33-52](https://user-images.githubusercontent.com/50574915/123356231-a5568700-d5aa-11eb-869b-636b1ef04afb.png)

**Comment by kodriscollics** [comment]
@ryanrosello-og ... Well, that's embarrassing! Great catch! 

It appears that the cy.get('#dataTable') call I'm using is only getting the header row...

<img width="882" alt="codeSnipett2" src="https://user-images.githubusercontent.com/75755773/123443450-2570f280-d593-11eb-9789-4f7b7f826e87.PNG">
 
<img width="919" alt="dataTableDebugger" src="https://user-images.githubusercontent.com/75755773/123443491-2dc92d80-d593-11eb-8b3c-7ab04da99075.PNG">

I'll delve into that.
Sorry about the churn!
Kent.

**Comment by kodriscollics** [comment]
@ryanrosello-og ... after examining the html for the webpage and experimenting with some test code, it looks to me that the way in which the html is coded for the page is not compatible with the isPropertySorted function. The html for the page doesn't include the header row within the <tbody> section. The header row is it's own section <thead>.  When I get the table, it is grabbing the header row but not the body with all the data rows. So, the following test passes:

<img width="929" alt="codeSnipettPass1" src="https://user-images.githubusercontent.com/75755773/123475813-29177000-d5b9-11eb-88f7-49b3c239bf34.PNG">

Interestingly though, since the header is a row, the following also passes because all the rows (tr) are being counted, including the header row:

<img width="808" alt="codeSnipettPass2" src="https://user-images.githubusercontent.com/75755773/123476028-6b40b180-d5b9-11eb-8217-7ec361b28ce2.PNG">

However, the following test fails because the header row isn't in the data:

<img width="901" alt="codeSnipetFail3" src="https://user-images.githubusercontent.com/75755773/123476306-c2468680-d5b9-11eb-8657-8a64836f5e3c.PNG">

This is shown by running the first test shown above which now fails:

<img width="1181" alt="codeSnipetFail2" src="https://user-images.githubusercontent.com/75755773/123476435-f4f07f00-d5b9-11eb-9dc8-dd1204202d56.PNG">

Here is a more complete view of the html page code:

<img width="1024" alt="debugSnipet2" src="https://user-images.githubusercontent.com/75755773/123478833-43534d00-d5bd-11eb-8fd7-32d47138f408.PNG">

**Comment by ryanrosello-og** [comment]
Sorry for the delayed response. was busy with life.

Would you be able to try changing your _waiting for data_ assertion to:

```javascript
    cy.get('#dataTable tr').should('have.length', 68)
    cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['task'], ['asc'])).to.be.true;
      });
```

- or 

```javascript
    cy.get('#dataTable tr').should('have.length.above', 0)
    cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['task'], ['asc'])).to.be.true;
      });
```

- or 

```javascript
    cy.intercept('api/endpoint/fetches/data').as('myTableData')
    cy.visit('https://myapp.com')
    cy.wait('@myTableData')
    cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['task'], ['asc'])).to.be.true;
      });
```

When you chain the `find('tr')`, an array of <tr> elements are passed into the plugin. The plugin then silently logs a warning since it only supports `<table>` tags:

<img width="1784" alt="should_fail_when_non_table_chained" src="https://user-images.githubusercontent.com/50574915/125184664-ee713100-e262-11eb-9b7d-420965389c51.png">

This is done since I did not want to throw an error directly inside the plugin because this would cause bad things to happen when running full suites of tests.  Maybe I should have?

I have also tried replicating your issue using my own static table below:

```html
<html>
<body >
  <table id="dataTable" border="1">
    <thead>
      <tr>
        <th>
          <input id="selectAll" type="checkbox" />
        </th>
        <th>
          <a>Task #</a>
        </th>     
        <th>
          <a>Unit Name</a>
        </th>    
        <th>
          <a>Date Rec</a>
        </th>       
        <th>
          <a>Type</a>
        </th>                           
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><input type="checkbox"/></td>
        <td>Ut</td>
        <td>05 Mar 19</td>
        <td>MLS</td>
        <td>Cl...</td>
      </tr>
      <tr>
        <td><input type="checkbox"/></td>
        <td>Zz 988</td>
        <td>07 Mar 19</td>
        <td>ALS</td>
        <td>Al...</td>
      </tr>            
      <tr>
        <td><input type="checkbox"/></td>
        <td>Yt</td>
        <td>06 Mar 19</td>
        <td>KLS</td>
        <td>Al...</td>
      </tr>      
    </tbody>
  </table>
</body>

</html>
```

*Spec*

```javascript
context('gh bug', () => {
  beforeEach(() => {
    cy.visit('./cypress/fixtures/table_bug.html');
  });

  it('table assertions', () => {
    cy.get('#dataTable tr').should('have.length.above', 0)
    cy.get('#dataTable')
      .scrapeTable()
      .then((table) => {
        expect(table.isPropertySorted(['task'], ['asc'])).to.be.true;
      });
  });
});

```

In my example, it was failing the assertion as expected:

<img width="1791" alt="2021-07-11_16-09-07" src="https://user-images.githubusercontent.com/50574915/125184725-7d7e4900-e263-11eb-8b4c-a2d04f39f0cf.png">

**Comment by kodriscollics** [comment]
ryanrosello-og no worries at all on the delay, I know how life goes. I've had plenty of other things to work on, so it's all good.

I tried what you suggested above and it works fine that way. I've modified my test code accordingly. 

Thanks for your patience and help!
